### ISSUE TITLE
How i access  the DCIM / Camera folder?

### ISSUE THREAD

**Issue by cesarbmolina** [protonet/cordova-plugin-image-resizer#39]
I would like to be able to access the DCIM / Camera folders and save my images there is some way to save my images in that folder

**Comment by JoschkaSchulz** [comment]
I havn't touched this repo for a while and couldn't find time to do it... but if I remember correctly you can name a folder (just on android because iOS don't know that concept of folders) and save it there... I'm not 100% sure if you could just name the DCIM/Camera folder so save the files inside that, but you can just take the resized files after the resize and move it to the specific folder.

**Comment by cesarbmolina** [comment]
it happens to me that when I save the image in a folder my native gallery does not update automatically to show me the images. it only shows me the images if I manually delete an old image and there I update the gallery. You have some idea of how you could solve this problem, Thanks.

**Comment by JoschkaSchulz** [comment]
hrm normally google photos should update instantly. I couldn't give support for gallery apps,... you could try to add the photos directly into the `/DCIM/subfolder` maybe that solves the problem. But sadly I can't see how I should fix that problem with the plugin.
